export const toolCatalog = [
  {
    id: "arms",
    name: "Arms",
    group: "Mechanisms",
    summary: "Rotating arms, pivots, linkage geometry, and load planning.",
    stage: "Planned",
    accent: "blue",
    futureSurfaces: ["Geometry", "Torque", "Motion profile"],
  },
  {
    id: "rollers",
    name: "Rollers",
    group: "Mechanisms",
    summary: "Roller speed targets, compression notes, and intake packaging.",
    stage: "Planned",
    accent: "green",
    futureSurfaces: ["Surface speed", "Compression", "Diameter"],
  },
  {
    id: "swerve",
    name: "Swerve Speeds",
    group: "Drivetrain",
    summary: "Module speed, free-speed estimates, and drive ratio checks.",
    stage: "Planned",
    accent: "orange",
    futureSurfaces: ["Wheel speed", "Gear ratio", "Motor free speed"],
  },
  {
    id: "elevators",
    name: "Elevators",
    group: "Mechanisms",
    summary: "Stage travel, carriage motion, rigging style, and lift targets.",
    stage: "Planned",
    accent: "teal",
    futureSurfaces: ["Travel", "Rigging", "Load"],
  },
  {
    id: "flywheels",
    name: "Flywheels",
    group: "Shooting",
    summary: "Wheel speed planning, recovery notes, and shooter packaging.",
    stage: "Planned",
    accent: "red",
    futureSurfaces: ["Exit speed", "Inertia", "Recovery"],
  },
  {
    id: "belts-chain",
    name: "Belts & Chain",
    group: "Power Transfer",
    summary: "Center distance, ratio planning, and packaging constraints.",
    stage: "Planned",
    accent: "gold",
    futureSurfaces: ["Center distance", "Ratio", "Wrap"],
  },
  {
    id: "gearing",
    name: "Gearing",
    group: "Power Transfer",
    summary: "Compound reductions, output speed targets, and packaging checks.",
    stage: "Planned",
    accent: "violet",
    futureSurfaces: ["Ratio stack", "Output speed", "Spacing"],
  },
  {
    id: "drivetrain",
    name: "Drivetrain",
    group: "Drivetrain",
    summary: "Drive speed targets, wheel choices, and reduction planning.",
    stage: "Planned",
    accent: "slate",
    futureSurfaces: ["Speed", "Traction", "Reduction"],
  },
];

export const buildNotes = [
  "Static files only",
  "No backend API",
  "No accounts",
  "No saved user data",
];
